name: CI
on: 
  push: 
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:        
          cache: 'npm'  
      - name: Build antora-ui
        run: |
          npm install
          gulp bundle
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.run_number }}
          commit: ${{ github.sha }}
          name: Release ${{ github.run_number }}
          artifacts: "build/ui-bundle.zip"        
          makeLatest: "latest"      
      - name: Trigger website update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TKIT_CI_PAT }}
          repository: 1000kit/1000kit.github.io
          event-type: dispatch-build-website